DROP DATABASE IF EXISTS db_todos;
CREATE DATABASE db_todos;
USE db_todos;
CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(64),
  email VARCHAR(254),
  password VARCHAR(254),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE todo (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  title VARCHAR(128),
  description TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (userId)
    REFERENCES user(id)
) ENGINE=INNODB;

CREATE TABLE star (
  userId INT NOT NULL,
  todoId INT NOT NULL,
  PRIMARY KEY (userId, todoId),
  FOREIGN KEY (userId) REFERENCES user(id),
  FOREIGN KEY (todoId) REFERENCES todo(id)
) ENGINE=INNODB;

